name: ping-meta
description: "Pings the robotpy-meta repository"
inputs:
  token:
    description: "Github repo access token"
    required: true
  version:
    description: "New version to ping"
    required: true
runs:
  using: "node12"
  main: dist/index.js
